---
title: "About Me"
output:
  html_document:
    toc: true
    toc_float: true
---


## About


In 2017, I received a BA in Public Health from the University of Washington. Currently, I am an MPH candidate at the Mailman School of Public Health in the Department of Population and Family Health where I am pursuing a certificate in Public Health Research Methods. I am a research assistant with the Care and Protection of Children Learning Network.

## Tools and Skills


**I am skilled in quantitative and qualitative analyses, program management, and program evaluation**

I have experience cleaning and conducting analyses on large datasets using R and SPSS; conducting qualitative research including coding and analyzing data in Dedoose; creating and fielding surveys in RedCAP and Qualtrics; and supporting program evaluations. 

I have direct experience supervising and hiring staff, managing multi-tiered projects, drafting grant applications and report; and communicating with corporate and government partners.

## Experience


Prior to pursuing my MPH, I was a project manager at the Urban Indian Health Institute where I supervised multiple staff, managed more than $2 million in Federal Grants, and supported the conduct of qualitative research and evaluations. In summer 2021, I interned with the International Rescue Committee's Airbel Impact Lab where I analyzed quantiative and qualitative data related to children's experiences with corporal punishment. Currently, I work with the CPC Learning Network where I support the creation of a Massive Open Online Course on the INSPIRE Strategies for Preventing Violence Against Children.

Outside of work, I am an avid cyclist and supporter of safe streets initatives. In 2019, I served on the Seattle Bicycle Advisory Board, where I advised the Seattle City Goverment on matters related to cycling and street safety. 