---
title: "Dashboard"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    theme: yeti
    navbar:
      - { title: "Home", href: index.html}
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(p8105.datasets)
library(plotly)
library(lubridate)
```

```{r}
data("rest_inspec")

nyc_rest <- rest_inspec  %>%
  rename(rest_id = camis, rest_name = dba) %>%
  mutate(boro = ifelse(boro == "Missing", NA, boro), boro = as.factor(boro), grade = factor(grade, labels = c("A", "B", "C", "P", "Z", "Not Yet Graded")), cuisine_description = as_factor(cuisine_description)) %>%
  select(boro, grade, score, rest_id, rest_name, cuisine_description, violation_description, violation_code, street, building, zipcode, inspection_date) %>%
  filter(inspection_date >= "2016-11-01") %>%
  drop_na(grade) %>%
  distinct(rest_id, .keep_all = TRUE) %>%
  mutate(address = str_c(building, " ", street, ", New York ", zipcode))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_rest %>%
  mutate(cuisine_description =  fct_collapse(cuisine_description, Latin = c("Latin (Cuban, Dominican, Puerto Rican, South & Central American)", "Peruvian"), Drink = "Bottled beverages, including water, sodas, juices, etc.", Sandwich = c("Sandwiches", "Sandwiches/Salads/Mixed Buffet"))) %>%
  mutate(grade = fct_collapse(grade, "Below A" = c("B", "C"))) %>%
  group_by(cuisine_description, grade) %>%
  summarize(n_grade = n()) %>%
  mutate(total = sum(n_grade), perc_failing = (n_grade/total) * 100) %>%
  filter(total >= 100, grade == "Below A") %>%
  mutate(cuisine_description = droplevels(cuisine_description)) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, perc_failing)) %>%
  plot_ly(y = ~cuisine_description, x = ~perc_failing,
          type = "bar", colors = "viridis") %>%
  layout(title = "Percent of Restaurants Below A Grade by Cuisine", xaxis = list(title ="% of Restaurants Below A"), yaxis = list(title = "Cuisine Type"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_rest %>%
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~boro, 
          type = "bar", colors = "viridis") %>%
  layout(title = "Number of Restaurants by Borough", xaxis = list(title ="Borough"), yaxis = list(title = "Number of Restaurants"))
```

### Chart C

```{r}
nyc_rest %>%
  mutate(vermin = ifelse(grepl('roaches|mice', violation_description), TRUE, FALSE)) %>%
  group_by(grade, vermin) %>%
  summarize(n = n()) %>%
  mutate(total = sum(n), perc_vermin = (n/total) * 100) %>%
  filter(vermin == TRUE) %>%
  plot_ly(x = ~grade, y = ~perc_vermin, type = "bar") %>%
  layout(title = "Percent of Restaurants with Vermin Present by Grade", xaxis = list(title ="Restaurant Grade"), yaxis = list(title = "% of Restaurants with Cockroaches or Rats Present"))
```

